GET http://localhost:8080/api/users
###


POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "admin4", 
    "password" : "admin"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "name": "admin1", 
    "password" : "admin"
}